### ISSUE TITLE
Shrine color palette

### ISSUE THREAD

**Issue by DastanIqbal** [c5inco/Shrine-Compose-Stream#1]
Hi, 

I still didn't understand, how this shrine palette created, when I am creating palette using Material Design color tools, values are different.  if anyone can help on this 

Primary color 50: #`FEEAE6`
https://material.io/design/color/the-color-system.html#tools-for-picking-colors

**Comment by c5inco** [comment]
Hi! The Shrine palette was created by manually picking color values and then mapping them to semantic keys, e.g. primary, secondary. 

The tools you linked above are to help you if you'd like to start with the Material 2014 color palette, and helps also with picking colors that are complementary. But you are not restricted to use just that.

**Comment by DastanIqbal** [comment]
Oh Nice Thanks
